### ISSUE TITLE
Following fails with pyhon3 but runs fine with python2

### ISSUE THREAD

**Issue by dilawar** [myhdl/myhdl#310]
Summary

```

import myhdl as hdl

@hdl.block
def MyExperiment():

    clk = hdl.Signal(0)

    @hdl.always(hdl.delay(1))
    def drive_clk():
        clk.next = not clk

    @hdl.always(clk.posedge)
    def test():
        print( "Zhandu balm" )

    return drive_clk, test


def main():
    inst = MyExperiment()
    inst.run_sim(50)

if __name__ == '__main__':
    main()

```

Now `python3 a.py` 

```
Traceback (most recent call last):
  File "iaf_hdl.py", line 13, in <module>
    import myhdl as hdl
  File "/home1/dilawars/.local/lib/python3.7/site-packages/myhdl/__init__.py", line 162, in <module>
    from ._always_seq import always_seq, ResetSignal
  File "/home1/dilawars/.local/lib/python3.7/site-packages/myhdl/_always_seq.py", line 48
    def __init__(self, val, active, async):
                                        ^
SyntaxError: invalid syntax

shell returned 1
```
But this runs fine with python2. 

## System information
```
MyHDL Version: 0.10
Python Version: 3.7
```

**Comment by dilawar** [comment]
Works fine when installed using `pip3 install git+https://github.com/myhdl/myhdl`. So I guess this has been fixed.
